export const Users = [
  {
    id:1,
    profilePicture: "assets/person/11.jpeg",
    username: "Rahul Prajapat",
  },
  {
    id:2,
    profilePicture: "assets/person/12.jpeg",
    username: "Aryan",
  },
  {
    id:3,
    profilePicture: "assets/person/14.jpeg",
    username: "Ayush Gupta",
  },
  {
    id:4,
    profilePicture: "assets/person/15.jpeg",
    username: "Devendra  Sahu",
  },
  {
    id:5,
    profilePicture: "assets/person/16.jpeg",
    username: "Abhishek Kumar",
  },
  {
    id:6,
    profilePicture: "assets/person/26.jpeg",
    username: "Prashant Agrawal",
  },
  {
    id:7,
    profilePicture: "assets/person/11.jpeg",
    username: "Rahul Prajapat",
  },
  {
    id:8,
    profilePicture: "assets/person/12.jpeg",
    username: "Aryan",
  },
  {
    id:9,
    profilePicture: "assets/person/15.jpeg",
    username: "Ayush gupta",
  },
  {
    id:10,
    profilePicture: "assets/person/16.jpeg",
    username: "Devendra Sahu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://source.unsplash.com/random?London",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://source.unsplash.com/random?mountains",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://source.unsplash.com/random?beach",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://source.unsplash.com/random?street",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://source.unsplash.com/random?cooking",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://source.unsplash.com/random?NewYork",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://source.unsplash.com/random?river",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://source.unsplash.com/random?planes",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://source.unsplash.com/random?picnic",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://source.unsplash.com/random?party",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];

